Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace ChapterOne.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;

namespace ChapterOne.Controllers
{
    public class OrderController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Checkout()
        {
            return View();
        }
    }
}

Views/Shared/Components/Header/Default.cshtml
@model HeaderVM

<header>
    <section class="slogan">
        <div class="container-custom">
            <div class="row ">
                <div class="col-6 text-left">
                    <p>@Model.Settings.FirstOrDefault(s=>s.Key == "Slogan").Value</p>
                </div>
                <div class="col icons">
                    <a href="">
                        <i class="fa-brands fa-instagram"></i>
                    </a>
                    <a href="">
                        <i class="fa-brands fa-facebook"></i>
                    </a>
                    <a href="">
                        <i class="fa-brands fa-twitter"></i>
                    </a>
                    <a href="">
                        <i class="fa-brands fa-youtube"></i>
                    </a>
                </div>
               
            </div>
        </div>
    </section>
    <nav>
        <div class="container-custom ">
            <div class="flex justify-content-between">

                <div class="nav-bar flex ">
                    <div class="logo">
                        <a asp-controller="Home" asp-action="Index">
                            <img src="@Model.Settings.FirstOrDefault(s=>s.Key=="Logo").Value" alt="">
                        </a>
                    </div>
                    <a asp-controller="Home" asp-action="Index">Home</a>
                    <a asp-controller="About" asp-action="Index">About Us</a>
                    <a asp-controller ="Events" asp-action="Index">
                        Events</a>
                    <a asp-controller="Product" asp-action="Index">Shop</a>
                </div>
                <div class="right d-flex align-items-center">
                    <div class="container h-100">
                        <div class="d-flex justify-content-center h-100">
                            <div class="searchbar">
                                <input id="searchInput" class="search_input" type="text" name="" placeholder="Search...">
                                <a href="#" class="search_icon"><i class="fas fa-search"></i></a>
                            </div>

                        </div>
                    </div>
                    <li class="nav-item m-auto py-2 ">
                        <div class="basket">
                            @await Html.PartialAsync("_BasketPartial",Model.BasketVMs)
                        </div>
                    </li>


                     <div class="dropdown col">
                    <button type="button" id="setting" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="fa-solid fa-user"></i></button>

                    <ul class="dropdown-menu" aria-labelledby="setting">
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Member"))
                            {

                                <li><a asp-controller="Account" asp-action="SignOut">Sign Out</a></li>
                                <li><a asp-controller="Order" asp-action="CheckOut">CheckOut</a></li>

                            }
                            else
                            {
                                <li style="color:black!important"><a asp-controller="Account" asp-action="Login">Sign In</a></li>
                                <li style="color:black"><a asp-controller="Account" asp-action="Register">Sign Up</a></li>
                            }
                    </ul>
                </div>

                </div>
            </div>
            <div class="d-flex justify-content-end" style="margin-right:100px">
                <ul id="searchBody">
                </ul>
            </div>
        </div>


    </nav>

</header>